modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="pubg"
version="1.1.1C"
displayName="PUBG Minecraft"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="icon.png"
authors="YiZhiMCQiu"
description='''
Author: YiZhiMCQiu
《我的世界：绝地求生》！
版本: 1.1.3
服务器版本: 1.1.3

主要更新/修复:
1.添加了购买系统, 现在未在服务器UUID列表内的UUID的Minecraft都会崩溃! ;)
'''
[[dependencies.pubg]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.pubg]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"